from typing import Optional


class INotifier:
    def info(self, message: str) -> None: ...
    def success(self, message: str) -> None: ...
    def error(self, message: str, exc: Optional[Exception] = None) -> None: ...
    def progress(self, current: int, total: int, label: str = "") -> None: ...
